pinata_api_key: ""
pinata_secret_api_key: ""
robonomics_path: ""
suri: ""
robonomics_remote: "wss://substrate.ipci.io"
interval: 30
temporal_username: "" # Temporal.Cloud credentials
temporal_password: ""
