#!/usr/bin/env python3
import requests
import rospy
import shutil
import os
import tempfile
from std_msgs.msg import Empty
from datetime import datetime
from rws_msgs.msg import Entry


class PhotoNode:

    def __init__(self):
        rospy.init_node("photo_node", anonymous=True)
        rospy.Subscriber("/takephoto", Empty, self.take_photo)
        self.entrypublisher = rospy.Publisher("/entry", Entry, queue_size=128)

        self.ip = rospy.get_param("~endpoint")
        self.tempdir = tempfile.TemporaryDirectory()

    def take_photo(self, data):
        self.now = datetime.now()
        timestamp = self.now.strftime("%Y-%m-%d-%H-%M-%S")

        rospy.loginfo("Downloading image...")

        filename = "photo-" + "-"+ timestamp + ".jpg" # + str(self.count) + "--"+ timestamp + ".jpg"

        full_filename = os.path.join(self.tempdir.name, filename)

        entry = Entry()
        try:
            res = requests.get(self.ip + "photoaf.jpg", stream=True)
            with open(full_filename, "wb") as f:
                shutil.copyfileobj(res.raw, f)
        except Exception as e:
            entry.action = str(e)
            entry.success = False
            rospy.logerr(e)
        else:
            rospy.loginfo(f"Finished {full_filename}")

            entry.action = f"Take a picture. File {full_filename}"
            entry.data = full_filename
            entry.success = True

        self.entrypublisher.publish(entry)

    def spin(self):
        rospy.spin()


if __name__ == "__main__":
    PhotoNode().spin()

